# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d25c5805aec43f8cb9096e45594d7d9bce6d99bd663287e43a0f3bf3b1872401b8cb7379af730b335ae5dae54b99f16cb88890661fa5126a1eb24971c1007f

test:
  secret_key_base: d45b902d720e33496274a06555943506afd0813e6c99dde60fdd7e534e9180029f900d60ac83e4ada1778ada31233d630ee76e8198d212aa1a51fb1c8f57f32f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
